name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:

jobs:
  test_on_host:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: apt hacks
      # the already installed libgd3 conflicts with libgd-dev to be installed
      # also, /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
        sudo apt-get remove -y libgd3 nginx
      if: "startsWith(matrix.os, 'ubuntu-')"

    - uses: actions/checkout@v2

    - name: "perl installation (macos)"
      run: |
        brew install cpanminus
      if: "startsWith(matrix.os, 'macos-')"

    - name: "perl installation (windows)"
      run: |
        if (!(Test-Path -Path "C:\strawberry")) {
          cinst strawberryperl
        }
      if: "startsWith(matrix.os, 'windows-')"

    - name: "perl installation (ubuntu)"
      run: |
        sudo apt-get install -q --no-install-recommends -y cpanminus
      if: "startsWith(matrix.os, 'ubuntu-')"

    - name: "build and test"
      run: |
        perl Makefile.PL
        make all test
